title: "Lorenzo — Portfolio"
description: "Software Developer • University of Arizona"
theme: minima

# Only show Projects in the top nav
header_pages:
  - projects.md

minima:
  social_links:
    - { platform: github,   user_url: "https://github.com/YOUR-USERNAME" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/YOUR-LINKEDIN/" }
