title: "Portfolio"
description: "Software Developer • University of Arizona"
theme: minima

# Only show Projects in the top nav
# header_pages:
 # - projects.md

minima:
  social_links:
    - { platform: linkedin, user_url: "www.linkedin.com/in/lorenzoharris214" }
    - { platform: github,   user_url: "https://github.com/Lozo214" }


